### ISSUE TITLE
sroie, test.py RuntimeError: Error(s) in loading state_dict for GatedGCNNet:

### ISSUE THREAD

**Issue by jingmouren** [cyh1112/GraphNormalization#1]
train.py runs ok.
and changed to resume from checkpoint runs ok too.
but test.py throws the following error.

Traceback (most recent call last):
  File "test.py", line 270, in <module>
    main()
  File "test.py", line 201, in main
    model = load_gate_gcn_net(device, checkpoint_path)
  File "test.py", line 187, in load_gate_gcn_net
    model.load_state_dict(checkpoint)

site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GatedGCNNet:
        Missing key(s) in state_dict: "layers.4.A.weight", "layers.4.A.bias", "layers.4.B.weight", "layers.4.B.bias", "layers.4.C.weight", "layers.4.C.bias", "layers.4.D.weight", "layers.4.D.bias", "layers.4.E.weight", "layers.4.E.bias", "layers.4.bn_node_h.gamma", "layers.4.bn_node_h.beta", "layers.4.bn_node_e.gamma", "layers.4.bn_node_e.beta", "layers.5.A.weight", "layers.5.A.bias", "layers.5.B.weight", "layers.5.B.bias", "layers.5.C.weight", "layers.5.C.bias", "layers.5.D.weight", "layers.5.D.bias", "layers.5.E.weight", "layers.5.E.bias", "layers.5.bn_node_h.gamma", "layers.5.bn_node_h.beta", "layers.5.bn_node_e.gamma", "layers.5.bn_node_e.beta", "dense_layers.4.bn.weight", "dense_layers.4.bn.bias", "dense_layers.4.linear.weight", "dense_layers.4.linear.bias", "dense_layers.5.bn.weight", "dense_layers.5.bn.bias", "dense_layers.5.linear.weight", "dense_layers.5.linear.bias".

**Comment by cyh1112** [comment]
function  load_gategcn_net in test.py is difference from train.py, change it to the same.

the released code may be a little different from our original code.

**Comment by cyh1112** [comment]
Hi, Jingmouren, thanks to pay attention to our work and thanks to point out this problem.

Function  load_gate_gcn_net in test.py is difference from train.py, just keep it consistent.
